### PR TITLE
CT-1465 Improve GPU selection

### PR DESCRIPTION
**Pull request by flebel**

### CODE REVIEW

**Comment by flebel** [comment]
@hoolymama @lawschlosser @jesseconductor this is still a WIP, but there only one remaining UX issue I am aware of. Please bring up any major issue before this gets out of draft as I'm still heavily testing the UI.

**Review by hoolymama — COMMENTED** [review]
For me, when it first starts, I get an error: 

```
# Warning: conductor.lib.common : Failed to load Conductor user preferences. You may want to reset your preferences from the options menu
Traceback (most recent call last):
  File "/Users/julian/dev/conductor/conductor_client/conductor/lib/common.py", line 86, in decorater_function
    return function(*args, **kwargs)
  File "/Users/julian/dev/conductor/conductor_client/conductor/submitter.py", line 1957, in loadSubmitterUserPrefs
    self.loadFileWidgetPrefs(source_filepath)
  File "/Users/julian/dev/conductor/conductor_client/conductor/lib/pyside_utils.py", line 1170, in loadFileWidgetPrefs
    widget = self.getWidgetByName(widget_name)
  File "/Users/julian/dev/conductor/conductor_client/conductor/lib/pyside_utils.py", line 1280, in getWidgetByName
    raise Exception("Expected widget not found: %s" % widget_name)
Exception: Expected widget not found: ui_instance_type_cmbx
 # 
```

### EDIT

I tried resetting global prefs, as suggested, but I still get the error.

**Comment by lawschlosser** [comment]
image
I find this implementation to be confusing. Here's why:
1. Why am I allowed to change the the gpu type (T4 Tensor), when there's no GPU count (None)? IMO this combobox should be disabled (when no gpu count is selected).
2. Populating the **CPU Cores** dropdown box with a bunch of other text, e.g.  _(GPU(s) available for this option)_, makes this much more difficult to comprehend IMO. Instead of describing to the user (via text), that there are other options,  we should just _show_ them (by populating the corresponding comboxes).   Yes, this has the downside of forcing the user to try a few different combobox options in order to find the combination that they want, but I think that's the better of the two evils. Having widgets that undo previous choices is not a great flow IMO.  I would suggest  a linear ux flow where the user starts at the top and works their way down...even if it means they may need to start over at the top again (if they find that there isn't an appealing combination).  But to alleviate that frustration, it's important to place the more important/restrictive items at the top of the flow.  This is why I suggested (via slack) to have the gpus at the top (as you have them), rather than at the bottom.  The reason being is that if a user is indeed in need of a GPU, that selection is going to likely have the most impact on their render (compared to the number of cpu cores or memory).

**Comment by lawschlosser** [comment]
image
In general, allowing the ui to ever exist in an invalid state is not a great idea.  If someone were to submit the job like this, what behavior is expected?

**Comment by lawschlosser** [comment]
> image
> In general, allowing the ui to ever exist in an invalid state is not a great idea. If someone were to submit the job like this, what behavior is expected?

Here's what currently happens:
```
# Traceback (most recent call last):
#   File "/home/lschlosser/git/conductor_client/conductor/submitter.py", line 974, in on_ui_submit_pbtn_clicked
#     response_code, response = self.runConductorSubmission(data)
#   File "/home/lschlosser/git/conductor_client/conductor/submitter_maya.py", line 629, in runConductorSubmission
#     return super(MayaConductorSubmitter, self).runConductorSubmission(data)
#   File "/home/lschlosser/git/conductor_client/conductor/submitter.py", line 888, in runConductorSubmission
#     conductor_args = self.generateConductorArgs(data)
#   File "/home/lschlosser/git/conductor_client/conductor/submitter_maya.py", line 580, in generateConductorArgs
#     conductor_args = super(MayaConductorSubmitter, self).generateConductorArgs(data)
#   File "/home/lschlosser/git/conductor_client/conductor/submitter.py", line 822, in generateConductorArgs
#     conductor_args["instance_type"] = self.getInstanceTypeForSelection()["name"]
#   File "/home/lschlosser/git/conductor_client/conductor/submitter.py", line 837, in getInstanceTypeForSelection
#     assert len(instances) == 1, "Selection should have returned at most one instance type, but returned %s: %s" % (len(instances), instances)
# AssertionError: Selection should have returned at most one instance type, but returned 24: [{u'cores': 2, u'memory': u'13', u'description': u'2 core, 13GB Mem', u'name': u'n1-highmem-2', u'gpu': None}, {u'cores': 32, u'memory': u'120', u'description': u'32 core, 120GB Mem', u'name': u'n1-standard-32', u'gpu': None}, {u'cores': 4, u'memory': u'15', u'description': u'4 core, 15GB Mem', u'name': u'n1-standard-4', u'gpu': None}, {u'cores': 96, u'memory': u'86.4', u'description': u'96 core, 86.4GB Mem', u'name': u'n1-highcpu-96', u'gpu': None}, {u'cores': 4, u'memory': u'3.6', u'description': u'4 core, 3.6GB Mem', u'name': u'n1-highcpu-4', u'gpu': None}, {u'cores': 16, u'memory': u'14.4', u'description': u'16 core, 14.4GB Mem', u'name': u'n1-highcpu-16', u'gpu': None}, {u'cores': 16, u'memory': u'104', u'description': u'16 core, 104GB Mem', u'name': u'n1-highmem-16', u'gpu': None}, {u'cores': 40, u'memory': u'961', u'description': u'40 core, 961GB Mem', u'name': u'n1-ultramem-40', u'gpu': None}, {u'cores': 64, u'memory': u'57.6', u'description': u'64 core, 57.6GB Mem', u'name': u'n1-highcpu-64', u'gpu': None}, {u'cores': 32, u'memory': u'28.8', u'description': u'32 core, 28.8GB Mem', u'name': u'n1-highcpu-32', u'gpu': None}, {u'cores': 32, u'memory': u'208', u'description': u'32 core, 208GB Mem', u'name': u'n1-highmem-32', u'gpu': None}, {u'cores': 160, u'memory': u'3844', u'description': u'160 core, 3844GB Mem', u'name': u'n1-ultramem-160', u'gpu': None}, {u'cores': 64, u'memory': u'416', u'description': u'64 core, 416GB Mem', u'name': u'n1-highmem-64', u'gpu': None}, {u'cores': 1, u'memory': u'3.8', u'description': u'1 core, 3.8GB Mem', u'name': u'n1-standard-1', u'gpu': None}, {u'cores': 8, u'memory': u'30', u'description': u'8 core, 30GB Mem', u'name': u'n1-standard-8', u'gpu': None}, {u'cores': 16, u'memory': u'60', u'description': u'16 core, 60GB Mem', u'name': u'n1-standard-16', u'gpu': None}, {u'cores': 96, u'memory': u'360', u'description': u'96 core, 360GB Mem', u'name': u'n1-standard-96', u'gpu': None}, {u'cores': 8, u'memory': u'52', u'description': u'8 core, 52GB Mem', u'name': u'n1-highmem-8', u'gpu': None}, {u'cores': 64, u'memory': u'240', u'description': u'64 core, 240GB Mem', u'name': u'n1-standard-64', u'gpu': None}, {u'cores': 96, u'memory': u'624', u'description': u'96 core, 624GB Mem', u'name': u'n1-highmem-96', u'gpu': None}, {u'cores': 80, u'memory': u'1922', u'description': u'80 core, 1922GB Mem', u'name': u'n1-ultramem-80', u'gpu': None}, {u'cores': 4, u'memory': u'26', u'description': u'4 core, 26GB Mem', u'name': u'n1-highmem-4', u'gpu': None}, {u'cores': 2, u'memory': u'7.5', u'description': u'2 core, 7.5GB Mem', u'name': u'n1-standard-2', u'gpu': None}, {u'cores': 8, u'memory': u'7.2', u'description': u'8 core, 7.2GB Mem', u'name': u'n1-highcpu-8', u'gpu': None}]
```

**Comment by lawschlosser** [comment]
> For me, when it first starts, I get an error:
> 
> ```
> # Warning: conductor.lib.common : Failed to load Conductor user preferences. You may want to reset your preferences from the options menu
> Traceback (most recent call last):
>   File "/Users/julian/dev/conductor/conductor_client/conductor/lib/common.py", line 86, in decorater_function
>     return function(*args, **kwargs)
>   File "/Users/julian/dev/conductor/conductor_client/conductor/submitter.py", line 1957, in loadSubmitterUserPrefs
>     self.loadFileWidgetPrefs(source_filepath)
>   File "/Users/julian/dev/conductor/conductor_client/conductor/lib/pyside_utils.py", line 1170, in loadFileWidgetPrefs
>     widget = self.getWidgetByName(widget_name)
>   File "/Users/julian/dev/conductor/conductor_client/conductor/lib/pyside_utils.py", line 1280, in getWidgetByName
>     raise Exception("Expected widget not found: %s" % widget_name)
> Exception: Expected widget not found: ui_instance_type_cmbx

@hoolymama yeah, that's just a warning.  It's expected behavior when trying to load prefs for an object in the ui that no longer exists (due to changes made by this PR).  I deleted my preferences via the **options** menu, and no longer get the error.
image

**Pull request closed without merging**
